DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS menus;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS restaurants;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS BIGINT START WITH 100000;

CREATE TABLE users (
   id 				BIGINT GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
   email 			VARCHAR(255)				NOT NULL,
   password 		VARCHAR(255) 				NOT NULL,
   role			    VARCHAR(255)	            NOT NULL
);

CREATE TABLE restaurants (
    id   	BIGINT GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name 	VARCHAR(70)		NOT NULL
);

CREATE TABLE menus (
   id               BIGINT GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
   date             DATE       NOT NULL,
   restaurant_id    BIGINT			NOT NULL,
   FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
) ;

CREATE TABLE menu_items (
    id              BIGINT GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    menu_id 		BIGINT			NOT NULL,
    name			VARCHAR(255)    NOT NULL,
    price			BIGINT			NOT NULL,
    FOREIGN KEY (menu_id) REFERENCES menus (id) ON DELETE CASCADE
);

CREATE TABLE votes (
   id                   BIGINT GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
   user_id 			    BIGINT			NOT NULL,
   restaurant_id 		BIGINT			NOT NULL,
   date 			    DATE		NOT NULL,
   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
   FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);